version: "3.9"
services:
  rootedcyber:
    build: .
    environment:
      REDIS_URI: $REDIS_URI
      REDIS_PASSWORD: $REDIS_PASSWORD
      SESSION: $SESSION
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      MONGO_URI: $MONGO_URI  # defaults to None
      BOT_TOKEN: $BOT_TOKEN # Not mandatory
      LOG_CHANNEL: $LOG_CHANNEL # Not mandatory
      DATABASE_URL: $DATABASE_URL  # defaults to None
      OKTETO: $OKTETO # whether Okteto or not
      BRANCH: $BRANCH # Custom Branch, just in some case
      OKTETO_TOKEN: $OKTETO_TOKEN
